version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "82:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: sh -c "chmod -R 775 /var/www/html/storage/logs && chown -R www-data:www-data /var/www/html/storage/logs && apache2-foreground"

  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee
      # MYSQL_USER: ${DB_USERNAME}  # Tidak diperlukan jika hanya menggunakan root
      # MYSQL_PASSWORD: ${DB_PASSWORD}  # Tidak diperlukan jika hanya menggunakan root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "85:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  dbdata:
